/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd.java.ch03.tic.tac.toe;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
